/* ─────────────────────────────────────────────
 *  Mock Products Data for Admin Panel
 *  Extended with admin fields (SKU, stock, sizes, etc.)
 * ───────────────────────────────────────────── */

import { Product } from "./types";

const IMG = "/images/collections";

export const mockProducts: Product[] = [
  {
    id: 1,
    name: "Kanjivaram Silk Saree",
    slug: "kanjivaram-silk-saree",
    image: `${IMG}/kanjivaram-silk.png`,
    price: 245,
    originalPrice: 390,
    rating: 5,
    reviews: 42,
    category: "Silk Sarees",
    badge: "New",
    description:
      "Luxurious golden Kanjivaram silk saree with rich zari work, perfect for weddings and festive occasions.",
    fabric: "Pure Silk",
    color: "Gold",
    inStock: true,
    createdAt: "2026-05-01",
    images: [
      "/images/products/kanjivaram-silk-saree/saree1_blue.jpeg",
      "/images/products/kanjivaram-silk-saree/saree1_green.jpeg",
      "/images/products/kanjivaram-silk-saree/saree1_purple.jpeg",
      "/images/products/kanjivaram-silk-saree/saree1_red.jpeg",
    ],
    colorVariants: [
      { name: "Royal Blue", hex: "#1e40af", image: "/images/products/kanjivaram-silk-saree/saree1_blue.jpeg" },
      { name: "Emerald Green", hex: "#16a34a", image: "/images/products/kanjivaram-silk-saree/saree1_green.jpeg" },
      { name: "Purple", hex: "#7c3aed", image: "/images/products/kanjivaram-silk-saree/saree1_purple.jpeg" },
      { name: "Red", hex: "#dc2626", image: "/images/products/kanjivaram-silk-saree/saree1_red.jpeg" },
    ],
    video: "/images/products/kanjivaram-silk-saree/0517.mp4",
    sku: "SB-KS-001",
    stock: 24,
    sizes: ["Free Size", "6.3m"],
    discountPercent: 37,
    isFeatured: true,
    isLatest: true,
    isTrending: false,
    specifications: {
      "Blouse Piece": "0.8m Unstitched",
      "Saree Length": "5.5m",
      "Wash Care": "Dry Clean Only",
      "Weave Type": "Handloom",
      "Zari Type": "Pure Gold Zari",
    },
    tags: ["wedding", "silk", "kanjivaram", "traditional"],
    weight: "650g",
    dimensions: "38 x 28 x 5 cm",
  },
  {
    id: 2,
    name: "Bridal Red Banarasi",
    slug: "bridal-red-banarasi",
    image: `${IMG}/bridal-banarasi.png`,
    price: 520,
    rating: 4.5,
    reviews: 128,
    category: "Bridal",
    description:
      "Stunning bridal red Banarasi silk saree with intricate gold zari brocade, a timeless wedding essential.",
    fabric: "Banarasi Silk",
    color: "Red",
    inStock: true,
    createdAt: "2026-04-15",
    sku: "SB-BR-002",
    stock: 12,
    sizes: ["Free Size"],
    isFeatured: true,
    isLatest: false,
    isTrending: true,
    specifications: {
      "Blouse Piece": "0.8m Unstitched",
      "Saree Length": "6.3m",
      "Wash Care": "Dry Clean Only",
      "Weave Type": "Jacquard",
    },
    tags: ["bridal", "wedding", "banarasi", "silk"],
    weight: "720g",
  },
  {
    id: 3,
    name: "Pastel Chanderi Cotton",
    slug: "pastel-chanderi-cotton",
    image: `${IMG}/chanderi-cotton.png`,
    price: 110,
    originalPrice: 180,
    rating: 4,
    reviews: 88,
    category: "Cotton Sarees",
    badge: "-15%",
    description:
      "Elegant pastel pink Chanderi cotton saree with delicate silver border, ideal for office and casual wear.",
    fabric: "Chanderi Cotton",
    color: "Pastel Pink",
    inStock: true,
    createdAt: "2026-04-20",
    sku: "SB-CC-003",
    stock: 45,
    sizes: ["Free Size", "5.5m", "6m"],
    discountPercent: 15,
    isFeatured: false,
    isLatest: true,
    isTrending: false,
    tags: ["cotton", "office", "casual", "chanderi"],
    weight: "380g",
  },
  {
    id: 4,
    name: "Emerald Georgette",
    slug: "emerald-georgette",
    image: `${IMG}/emerald-georgette.png`,
    price: 185,
    rating: 4.5,
    reviews: 89,
    category: "Handloom",
    description:
      "Rich emerald green Georgette saree with gold embroidery border, a stunning pick for evening events.",
    fabric: "Georgette",
    color: "Emerald Green",
    inStock: true,
    createdAt: "2026-04-10",
    sku: "SB-EG-004",
    stock: 8,
    sizes: ["Free Size"],
    isFeatured: false,
    isLatest: false,
    isTrending: true,
    tags: ["georgette", "party", "evening", "embroidery"],
    weight: "420g",
  },
  {
    id: 5,
    name: "Tussar Silk Heritage",
    slug: "tussar-silk-heritage",
    image: `${IMG}/tussar-silk.png`,
    price: 320,
    originalPrice: 450,
    rating: 5,
    reviews: 64,
    category: "Silk Sarees",
    badge: "Best Seller",
    description:
      "Beautiful tussar silk saree in beige and gold tones with traditional Madhubani-inspired prints.",
    fabric: "Tussar Silk",
    color: "Beige Gold",
    inStock: true,
    createdAt: "2026-03-25",
    sku: "SB-TS-005",
    stock: 18,
    sizes: ["Free Size", "6m"],
    discountPercent: 29,
    isFeatured: true,
    isLatest: false,
    isTrending: true,
    specifications: {
      "Blouse Piece": "0.8m Unstitched",
      "Saree Length": "5.5m",
      "Wash Care": "Dry Clean Recommended",
      "Weave Type": "Hand Block Print",
    },
    tags: ["tussar", "silk", "heritage", "madhubani"],
    weight: "490g",
  },
  {
    id: 6,
    name: "Royal Banarasi Brocade",
    slug: "royal-banarasi-brocade",
    image: `${IMG}/bridal-banarasi.png`,
    price: 680,
    rating: 5,
    reviews: 156,
    category: "Bridal",
    description:
      "Premium royal Banarasi brocade saree with heavy gold zari throughout, a statement piece for grand celebrations.",
    fabric: "Banarasi Silk",
    color: "Deep Red",
    inStock: true,
    createdAt: "2026-03-20",
    sku: "SB-RB-006",
    stock: 5,
    sizes: ["Free Size", "6.3m", "8m"],
    isFeatured: true,
    isLatest: false,
    isTrending: false,
    tags: ["royal", "bridal", "banarasi", "brocade"],
    weight: "800g",
  },
  {
    id: 7,
    name: "Soft Cotton Handloom",
    slug: "soft-cotton-handloom",
    image: `${IMG}/chanderi-cotton.png`,
    price: 95,
    originalPrice: 140,
    rating: 4,
    reviews: 73,
    category: "Cotton Sarees",
    description:
      "Soft handloom cotton saree with gentle weave patterns, perfect for everyday elegance and comfort.",
    fabric: "Cotton",
    color: "Light Pink",
    inStock: true,
    createdAt: "2026-04-05",
    sku: "SB-SC-007",
    stock: 62,
    sizes: ["Free Size", "5.5m"],
    discountPercent: 32,
    isFeatured: false,
    isLatest: true,
    isTrending: false,
    tags: ["cotton", "handloom", "daily", "comfort"],
    weight: "320g",
  },
  {
    id: 8,
    name: "Pure Silk Kanjivaram",
    slug: "pure-silk-kanjivaram",
    image: `${IMG}/kanjivaram-silk.png`,
    price: 410,
    rating: 4.5,
    reviews: 102,
    category: "Silk Sarees",
    description:
      "Authentic pure silk Kanjivaram with temple border motifs, hand-woven by master artisans of Kanchipuram.",
    fabric: "Pure Silk",
    color: "Gold",
    inStock: true,
    createdAt: "2026-03-15",
    sku: "SB-PK-008",
    stock: 15,
    sizes: ["Free Size", "6.3m"],
    isFeatured: false,
    isLatest: false,
    isTrending: true,
    tags: ["kanjivaram", "silk", "temple", "artisan"],
    weight: "680g",
  },
  {
    id: 9,
    name: "Designer Georgette Party",
    slug: "designer-georgette-party",
    image: `${IMG}/emerald-georgette.png`,
    price: 210,
    originalPrice: 290,
    rating: 4,
    reviews: 55,
    category: "Daily Wear",
    badge: "-28%",
    description:
      "Contemporary designer Georgette saree with modern prints, a versatile choice for parties and gatherings.",
    fabric: "Georgette",
    color: "Green",
    inStock: false,
    createdAt: "2026-04-25",
    sku: "SB-DG-009",
    stock: 0,
    sizes: ["Free Size"],
    discountPercent: 28,
    isFeatured: false,
    isLatest: true,
    isTrending: false,
    tags: ["designer", "georgette", "party", "modern"],
    weight: "390g",
  },
  {
    id: 10,
    name: "Golden Tussar Weave",
    slug: "golden-tussar-weave",
    image: `${IMG}/tussar-silk.png`,
    price: 275,
    rating: 4.5,
    reviews: 47,
    category: "Handloom",
    description:
      "Handloom Tussar silk with golden weave patterns, a heritage piece showcasing traditional craftsmanship.",
    fabric: "Tussar Silk",
    color: "Golden Beige",
    inStock: true,
    createdAt: "2026-04-12",
    sku: "SB-GT-010",
    stock: 22,
    sizes: ["Free Size", "6m"],
    isFeatured: false,
    isLatest: false,
    isTrending: false,
    tags: ["tussar", "handloom", "golden", "heritage"],
    weight: "510g",
  },
  {
    id: 11,
    name: "Festive Red Banarasi",
    slug: "festive-red-banarasi",
    image: `${IMG}/bridal-banarasi.png`,
    price: 550,
    originalPrice: 720,
    rating: 5,
    reviews: 91,
    category: "Bridal",
    badge: "Trending",
    description:
      "Festive red Banarasi saree with intricate gold motifs, a crowd favorite for weddings and celebrations.",
    fabric: "Banarasi Silk",
    color: "Red",
    inStock: true,
    createdAt: "2026-05-05",
    sku: "SB-FR-011",
    stock: 3,
    sizes: ["Free Size", "6.3m", "8m"],
    discountPercent: 24,
    isFeatured: true,
    isLatest: true,
    isTrending: true,
    tags: ["festive", "bridal", "banarasi", "wedding"],
    weight: "750g",
  },
  {
    id: 12,
    name: "Daily Comfort Cotton",
    slug: "daily-comfort-cotton",
    image: `${IMG}/chanderi-cotton.png`,
    price: 75,
    rating: 4,
    reviews: 134,
    category: "Daily Wear",
    description:
      "Lightweight cotton saree for daily comfort, easy to drape with a soft finish for all-day wear.",
    fabric: "Cotton",
    color: "Pastel",
    inStock: true,
    createdAt: "2026-04-28",
    sku: "SB-DC-012",
    stock: 85,
    sizes: ["Free Size", "5.5m", "6m"],
    isFeatured: false,
    isLatest: false,
    isTrending: false,
    tags: ["cotton", "daily", "comfort", "lightweight"],
    weight: "280g",
  },
];
